/* Code generated by cmd/cgo; DO NOT EDIT. */

#include <stdlib.h>
#include "_cgo_export.h"

#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wpragmas"
#pragma GCC diagnostic ignored "-Waddress-of-packed-member"
extern void crosscall2(void (*fn)(void *), void *, int, __SIZE_TYPE__);
extern __SIZE_TYPE__ _cgo_wait_runtime_init_done(void);
extern void _cgo_release_context(__SIZE_TYPE__);

extern char* _cgo_topofstack(void);
#define CGO_NO_SANITIZE_THREAD
#define _cgo_tsan_acquire()
#define _cgo_tsan_release()


#define _cgo_msan_write(addr, sz)

extern void _cgoexp_a66a9425af73_GoRealDataCallBack(void *);

CGO_NO_SANITIZE_THREAD
void GoRealDataCallBack(int lRealHandle, unsigned int dwDataType, unsigned char* pBuffer, unsigned int dwBufSize, void* pUser)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		int p0;
		unsigned int p1;
		unsigned char* p2;
		unsigned int p3;
		char __pad0[4];
		void* p4;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = lRealHandle;
	_cgo_a.p1 = dwDataType;
	_cgo_a.p2 = pBuffer;
	_cgo_a.p3 = dwBufSize;
	_cgo_a.p4 = pUser;
	_cgo_tsan_release();
	crosscall2(_cgoexp_a66a9425af73_GoRealDataCallBack, &_cgo_a, 32, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_a66a9425af73_GoCatchErrorCallback(void *);

CGO_NO_SANITIZE_THREAD
void GoCatchErrorCallback(unsigned int dwType, int lUserID, int lHandle, void* pUser)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		unsigned int p0;
		int p1;
		int p2;
		char __pad0[4];
		void* p3;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = dwType;
	_cgo_a.p1 = lUserID;
	_cgo_a.p2 = lHandle;
	_cgo_a.p3 = pUser;
	_cgo_tsan_release();
	crosscall2(_cgoexp_a66a9425af73_GoCatchErrorCallback, &_cgo_a, 24, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_a66a9425af73_GoAlarmMsgCallback(void *);

CGO_NO_SANITIZE_THREAD
GoUint8 GoAlarmMsgCallback(int lCommand, void* pAlarmer, char* pAlarmInfo, unsigned int dwBufLen, void* pUser)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		int p0;
		char __pad0[4];
		void* p1;
		char* p2;
		unsigned int p3;
		char __pad1[4];
		void* p4;
		GoUint8 r0;
	} __attribute__((__packed__, __gcc_struct__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = lCommand;
	_cgo_a.p1 = pAlarmer;
	_cgo_a.p2 = pAlarmInfo;
	_cgo_a.p3 = dwBufLen;
	_cgo_a.p4 = pUser;
	_cgo_tsan_release();
	crosscall2(_cgoexp_a66a9425af73_GoAlarmMsgCallback, &_cgo_a, 41, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
	return _cgo_a.r0;
}
