// Code generated by cmd/cgo; DO NOT EDIT.

package haikang

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_char int8

type _Ctype_int int32

//go:notinheap
type _Ctype_struct_NET_DVR_ALARMER struct{}

//go:notinheap
type _Ctype_struct_RealPlayInfo struct{}

type _Ctype_uchar uint8

type _Ctype_uint uint32

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})

//go:cgo_export_dynamic GoRealDataCallBack
//go:linkname _cgoexp_a66a9425af73_GoRealDataCallBack _cgoexp_a66a9425af73_GoRealDataCallBack
//go:cgo_export_static _cgoexp_a66a9425af73_GoRealDataCallBack
func _cgoexp_a66a9425af73_GoRealDataCallBack(a *struct {
		p0 _Ctype_int
		p1 _Ctype_uint
		p2 *_Ctype_uchar
		p3 _Ctype_uint
		p4 unsafe.Pointer
	}) {
GoRealDataCallBack(a.p0, a.p1, a.p2, a.p3, a.p4)
}
//go:cgo_export_dynamic GoCatchErrorCallback
//go:linkname _cgoexp_a66a9425af73_GoCatchErrorCallback _cgoexp_a66a9425af73_GoCatchErrorCallback
//go:cgo_export_static _cgoexp_a66a9425af73_GoCatchErrorCallback
func _cgoexp_a66a9425af73_GoCatchErrorCallback(a *struct {
		p0 _Ctype_uint
		p1 _Ctype_int
		p2 _Ctype_int
		p3 unsafe.Pointer
	}) {
GoCatchErrorCallback(a.p0, a.p1, a.p2, a.p3)
}
//go:cgo_export_dynamic GoAlarmMsgCallback
//go:linkname _cgoexp_a66a9425af73_GoAlarmMsgCallback _cgoexp_a66a9425af73_GoAlarmMsgCallback
//go:cgo_export_static _cgoexp_a66a9425af73_GoAlarmMsgCallback
func _cgoexp_a66a9425af73_GoAlarmMsgCallback(a *struct {
		p0 _Ctype_int
		p1 unsafe.Pointer
		p2 *_Ctype_char
		p3 _Ctype_uint
		p4 unsafe.Pointer
		r0 bool
	}) {
	a.r0 = GoAlarmMsgCallback(a.p0, a.p1, a.p2, a.p3, a.p4)
}
