// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/zhaoxuewang/go_device_haikang/app/api/haikang/gocallback.go:1:1
package haikang

import _ "unsafe"
import (
	"unsafe"
	"fmt"
)

//export GoRealDataCallBack
func GoRealDataCallBack(lRealHandle  /*line :10:37*/_Ctype_int /*line :10:42*/, dwDataType  /*line :10:55*/_Ctype_uint /*line :10:61*/, pBuffer * /*line :10:72*/_Ctype_uchar /*line :10:79*/, dwBufSize  /*line :10:91*/_Ctype_uint /*line :10:97*/, pUser unsafe.Pointer) {
	fmt.Println("GoRealDataCallBack")
	fmt.Println( /*line :12:14*/_Ctype_uint /*line :12:20*/(dwBufSize))
	fmt.Println((* /*line :13:16*/_Ctype_char /*line :13:22*/)(unsafe.Pointer(pBuffer)))
	fmt.Println( /*line :14:14*/_Ctype_int /*line :14:19*/(lRealHandle))
	fmt.Println( /*line :15:14*/_Ctype_uint /*line :15:20*/(dwDataType))
	fmt.Println((* /*line :16:16*/_Ctype_struct_RealPlayInfo /*line :16:37*/)(pUser))
	return
}

//export GoCatchErrorCallback
func GoCatchErrorCallback(dwType  /*line :21:34*/_Ctype_uint /*line :21:40*/, lUserID  /*line :21:50*/_Ctype_int /*line :21:55*/, lHandle  /*line :21:65*/_Ctype_int /*line :21:70*/, pUser unsafe.Pointer) {
	fmt.Println("GoCatchErrorCallback")
	// EXCEPTION_RECONNECT
	fmt.Println( /*line :24:14*/_Ctype_uint /*line :24:20*/(dwType))
	fmt.Println( /*line :25:14*/_Ctype_int /*line :25:19*/(lHandle))
	fmt.Println( /*line :26:14*/_Ctype_int /*line :26:19*/(lUserID))
	fmt.Println((* /*line :27:16*/_Ctype_uint /*line :27:22*/)(pUser))
	return
}

//export GoAlarmMsgCallback
func GoAlarmMsgCallback(lCommand  /*line :32:34*/_Ctype_int /*line :32:39*/, pAlarmer unsafe.Pointer, pAlarmInfo * /*line :32:78*/_Ctype_char /*line :32:84*/, dwBufLen  /*line :32:95*/_Ctype_uint /*line :32:101*/, pUser unsafe.Pointer) bool {
	fmt.Println("GoAlarmMsgCallback")
	fmt.Println( /*line :34:14*/_Ctype_int /*line :34:19*/(lCommand))
	fmt.Println((* /*line :35:16*/_Ctype_char /*line :35:22*/)(pAlarmInfo))
	fmt.Println((* /*line :36:16*/_Ctype_struct_NET_DVR_ALARMER /*line :36:40*/)(pAlarmer))
	fmt.Println( /*line :37:14*/_Ctype_uint /*line :37:20*/(dwBufLen))
	fmt.Println((* /*line :38:16*/_Ctype_uint /*line :38:22*/)(pUser))
	return false
}
